# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Speak-AI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftReorder', '~> 7.2'
pod "RappleProgressHUD"
pod 'ApphudSDK', '3.1.0'
  # Pods for Speak-AI

end
